name: Reusable Hello World Workflow

# This makes the workflow reusable by other workflows
on:
  workflow_call:
    # Optional inputs that calling workflows can pass    
    # Optional outputs that calling workflows can use
    outputs:
      greeting:
        description: "The greeting message"
        value: ${{ jobs.hello.outputs.greeting }}

jobs:
  hello:
    name: Hello World Job reusable workflow
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        id: greet
        run: |
          # Set output for other jobs to use
          greeting="called the reusable workflows"

      
